config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  devise_for :users

  resources :projects, param: :project_id
  resources :projects, only: [] do
    resources :translations, only: %i[index create update], param: :translation_id
    resources :translation_uploads, only: %i[create]
  end
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  belongs_to :user
  belongs_to :primary_language, class_name: Language.name
  has_and_belongs_to_many :languages
  has_many :translations

  validates :name, presence: true
  validates :primary_language, presence: true
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# All of the logic for the projects.
# URL: /projects
class ProjectsController < ApplicationController
  include ProjectAware

  before_action :authenticate_user!

  # @return [void]
  def index
    @projects = Project.includes(:primary_language).where(user_id: current_user.id)
  end

  def new
    @project = Project.new
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      respond_with @project, status: :unprocessable_entity
    end
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    if @project.save
      redirect_to projects_path
    else
      respond_with @project, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :primary_language_id, language_ids: [])
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with model: @project do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% if @project.errors.include?(:name) %>
      <p><%= @project.errors.where(:name).first.full_message %></p>
    <% end %>
  </div>

  <% languages_array = Language.all.map { |language| [t(language.code), language.id, ] } %>
  <div>
    <%= form.label :primary_language_id %>
    <%= form.select(:primary_language_id, languages_array, {}, { class: "custom-select" }) %>
    <% if @project.errors.include?(:primary_language) %>
      <p><%= @project.errors.where(:primary_language).first.full_message %></p>
    <% end %>
  </div>

  <div>
    <%= form.label :language_ids %>
    <%= form.select(:language_ids, languages_array, {}, { multiple: true, size: 1, class: "custom-select" }) %>
  </div>

  <button class="w-100">Submit</button>
<% end %>

app/views/projects/edit.html.erb
<%= render "form" %>

app/views/projects/index.html.erb
<% if @projects.empty? %>
  <div class="text-center">
    <h2>No projects</h2>
  </div>
  <div class="text-center">
    <a role="button" href="<%= new_project_path %>">Create your first project</a>
  </div>
<% else %>
  <div class="flex m-4 justify-content-between">
    <div>
      <h1>Projects</h1>
    </div>
    <a role="button" href="<%= new_project_path %>">New project</a>
  </div>
  <div class="app-grid">
    <% @projects.each do |project| %>
      <article class="p-4">
        <h3> Name: <%= project.name %> </h3>
        <h4>Language: <%= t(project.primary_language.code) %></h4>

        <div class="flex justify-content-between mt-3">
          <div></div>
          <div>
            <a class="icon me-3" href="<%= project_translations_path(project) %>" data-tooltip="View Project"><i class="lni lni-eye"></i></a>
            <a class="icon" href="<%= edit_project_path(project) %>" data-tooltip="Edit Project"><i class="lni lni-pencil"></i></a>
          </div>
        </div>
      </article>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<%= render "form" %>