config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
  devise_for :users

  resources :projects, param: :project_id
  resources :projects, only: [] do
    resources :translations, only: %i[index create update], param: :translation_id
    resources :translation_uploads, only: %i[create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TranslationX</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="container">
    <nav class="px-3">
      <ul>
        <li><strong>TranslationX</strong></li>
      </ul>
      <ul>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Projects",  projects_path %>
          </li>
          <li>
            <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path  %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path  %>
          </li>
        <% end %>
      </ul>
    </nav>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

    <div class="notification-container"></div>
  </body>
</html>